name: Deploy to GitHub Pages

on:
  push:
    branches: ["main"]
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: false

jobs:
  build:
    runs-on: macos-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: "20"
          cache: 'npm'

      - name: Setup Pages
        uses: actions/configure-pages@v4
        with:
          static_site_generator: next

      - name: Install dependencies
        run: npm ci

      - name: Build with Next.js
        run: npm run build
        env:
          NEXT_TELEMETRY_DISABLED: 1

      - name: Create static export
        run: |
          echo "Checking build output..."
          if [ ! -d "out" ]; then
            echo "out directory not found, checking .next..."
            if [ -d ".next/server/app" ]; then
              echo "Creating out directory from .next/server/app"
              mkdir -p out
              cp -r .next/server/app/* out/ || echo "No app files to copy"
              cp -r .next/static out/_next 2>/dev/null || echo "No static files"
              cp -r public/* out/ 2>/dev/null || echo "No public files"
            else
              echo "ERROR: Neither out nor .next/server/app exists!"
              exit 1
            fi
          else
            echo "out directory exists, size: $(du -sh out | cut -f1)"
          fi
          echo "Final out directory contents:"
          ls -la out/

      - name: Upload artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: ./out

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: macos-latest
    needs: build
    steps:
      - name: Deploy to GitHub Pages
        id: deployment
        uses: actions/deploy-pages@v4
